var map = [
    'WWWWWWWWWWWWWWWWWWWWWWWWW',
    'W                       W',
    'W                       W',
    'W                       W',
    'W                       W ',
    'W                        ',
    'W                        ',
    'W                        ',
    'W                        ',
    'W                        ',
    'W                       W',
    'W                       W',
    'W                       W',
    'WWW                     W',
    'W                       W',
    'W        9              W',
    'W                       W',
    'WP                      W',
    'WWWWWWWWWWWWWWWWWWWWWWWWW'
];